// E-commerce keywords and comparisons config

export const ecommerceKeywords = [
  { slug: "متجر-الكتروني", nameAr: "متجر إلكتروني", nameEn: "Ecommerce Store" },
  { slug: "تصميم-متجر", nameAr: "تصميم متجر", nameEn: "Store Design" },
  { slug: "انشاء-متجر", nameAr: "إنشاء متجر", nameEn: "Create Store" },
  { slug: "موقع-تجارة", nameAr: "موقع تجارة", nameEn: "Commerce Website" },
  { slug: "افضل-منصة-تجارة", nameAr: "أفضل منصة تجارة", nameEn: "Best Ecommerce Platform" },
  { slug: "متجر-سريع", nameAr: "متجر سريع", nameEn: "Fast Store" },
  { slug: "متجر-بدون-عمولة", nameAr: "متجر بدون عمولة", nameEn: "No Commission Store" },
  { slug: "بديل-سلة", nameAr: "بديل سلة", nameEn: "Salla Alternative" },
  { slug: "بديل-زد", nameAr: "بديل زد", nameEn: "Zid Alternative" },
  { slug: "بديل-ووردبريس", nameAr: "بديل ووردبريس", nameEn: "WordPress Alternative" },
  { slug: "ecommerce-website", nameAr: "موقع إيكومرس", nameEn: "Ecommerce Website" },
  { slug: "woocommerce-alternative", nameAr: "بديل ووكومرس", nameEn: "WooCommerce Alternative" },
  { slug: "متجر-nextjs", nameAr: "متجر Next.js", nameEn: "Next.js Store" },
  { slug: "متجر-احترافي", nameAr: "متجر احترافي", nameEn: "Professional Store" },
  { slug: "تطوير-متجر", nameAr: "تطوير متجر", nameEn: "Store Development" },
  { slug: "برمجة-متجر", nameAr: "برمجة متجر", nameEn: "Store Programming" },
  { slug: "متجر-مخصص", nameAr: "متجر مخصص", nameEn: "Custom Store" },
  { slug: "متجر-سعودي", nameAr: "متجر سعودي", nameEn: "Saudi Store" },
  { slug: "شركة-متاجر", nameAr: "شركة متاجر", nameEn: "Store Company" },
  { slug: "تكلفة-متجر", nameAr: "تكلفة متجر", nameEn: "Store Cost" }
]

// Alias for backward compatibility with existing sitemap
export const storeTypes = ecommerceKeywords

// Ecommerce solutions (for backward compatibility)
export const ecommerceSolutions = [
  { slug: "fast-ecommerce", titleAr: "متجر سريع", descAr: "أسرع متجر إلكتروني في السعودية" },
  { slug: "seo-optimized", titleAr: "متجر محسّن SEO", descAr: "متجر يظهر أول في جوجل" },
  { slug: "no-commission", titleAr: "بدون عمولات", descAr: "متجر بدون أي رسوم على المبيعات" },
  { slug: "custom-store", titleAr: "متجر مخصص", descAr: "متجر مصمم خصيصاً لعلامتك التجارية" },
]

export const platformComparisons = [
  {
    slug: "wordpress-vs-nextjs",
    competitor: "WordPress",
    competitorAr: "ووردبريس",
    titleAr: "ووردبريس vs Next.js - لماذا Next.js أفضل؟",
    titleEn: "WordPress vs Next.js - Why Next.js is Better?",
    descriptionAr: "مقارنة شاملة بين WordPress و Next.js للمتاجر الإلكترونية. اكتشف لماذا Next.js أسرع، أأمن، وأفضل لـ SEO",
    competitorSpeed: 4.2,
    nextjsSpeed: 0.8,
    competitorSEO: 60,
    nextjsSEO: 98,
    competitorSecurity: 40,
    nextjsSecurity: 99,
    competitorCost: 15000,
    nextjsCost: 6000,
    problems: [
      "بطء شديد في التحميل (4+ ثواني)",
      "ثغرات أمنية مستمرة",
      "تحتاج تحديثات وصيانة دائمة",
      "Plugins مدفوعة وتضارب بينها",
      "فشل في Core Web Vitals"
    ]
  },
  {
    slug: "salla-vs-nextjs",
    competitor: "Salla",
    competitorAr: "سلة",
    titleAr: "سلة vs Next.js - تخلص من العمولات!",
    titleEn: "Salla vs Next.js - Get Rid of Commissions!",
    descriptionAr: "مقارنة بين سلة و Next.js. اكتشف كيف توفر آلاف الريالات بالتخلص من عمولات سلة",
    competitorSpeed: 2.5,
    nextjsSpeed: 0.8,
    competitorSEO: 60,
    nextjsSEO: 98,
    competitorSecurity: 80,
    nextjsSecurity: 99,
    competitorCost: 12000,
    nextjsCost: 6000,
    hasCommission: true,
    commissionRate: "2-5%",
    problems: [
      "عمولة على كل عملية بيع (2-5%)",
      "تخصيص محدود جداً",
      "لا تملك موقعك - مستأجر",
      "صعوبة التميز عن المنافسين",
      "SEO محدود"
    ]
  },
  {
    slug: "zid-vs-nextjs",
    competitor: "Zid",
    competitorAr: "زد",
    titleAr: "زد vs Next.js - حرية بدون قيود!",
    titleEn: "Zid vs Next.js - Freedom Without Limits!",
    descriptionAr: "مقارنة بين زد و Next.js. اكتشف لماذا Next.js يمنحك الحرية الكاملة بدون عمولات",
    competitorSpeed: 2.3,
    nextjsSpeed: 0.8,
    competitorSEO: 55,
    nextjsSEO: 98,
    competitorSecurity: 80,
    nextjsSecurity: 99,
    competitorCost: 14000,
    nextjsCost: 6000,
    hasCommission: true,
    commissionRate: "1-2%",
    problems: [
      "عمولة 1-2% على المبيعات",
      "قوالب محدودة جداً",
      "تكاليف إضافية للميزات",
      "صعوبة التخصيص",
      "لا تملك الكود"
    ]
  },
  {
    slug: "woocommerce-vs-nextjs",
    competitor: "WooCommerce",
    competitorAr: "ووكومرس",
    titleAr: "ووكومرس vs Next.js - الفرق الحقيقي",
    titleEn: "WooCommerce vs Next.js - The Real Difference",
    descriptionAr: "مقارنة تفصيلية بين WooCommerce و Next.js. لماذا Next.js هو مستقبل التجارة الإلكترونية",
    competitorSpeed: 3.8,
    nextjsSpeed: 0.8,
    competitorSEO: 65,
    nextjsSEO: 98,
    competitorSecurity: 50,
    nextjsSecurity: 99,
    competitorCost: 12000,
    nextjsCost: 6000,
    problems: [
      "يعتمد على WordPress البطيء",
      "Plugins كثيرة ومشاكل توافق",
      "ثغرات أمنية متكررة",
      "يحتاج صيانة مستمرة",
      "أداء ضعيف مع المنتجات الكثيرة"
    ]
  },
  {
    slug: "shopify-vs-nextjs",
    competitor: "Shopify",
    competitorAr: "شوبيفاي",
    titleAr: "شوبيفاي vs Next.js - الحقيقة الكاملة",
    titleEn: "Shopify vs Next.js - The Complete Truth",
    descriptionAr: "مقارنة بين Shopify و Next.js. لماذا الشركات الكبرى تنتقل لـ Next.js",
    competitorSpeed: 2.0,
    nextjsSpeed: 0.8,
    competitorSEO: 70,
    nextjsSEO: 98,
    competitorSecurity: 90,
    nextjsSecurity: 99,
    competitorCost: 18000,
    nextjsCost: 6000,
    hasCommission: true,
    commissionRate: "0.5-2%",
    problems: [
      "تكلفة شهرية عالية",
      "عمولة على المبيعات",
      "تخصيص يحتاج Liquid",
      "غير محلي للسوق السعودي",
      "دعم فني بالإنجليزي فقط"
    ]
  },
  {
    slug: "magento-vs-nextjs",
    competitor: "Magento",
    competitorAr: "ماجنتو",
    titleAr: "ماجنتو vs Next.js - البديل الأذكى",
    titleEn: "Magento vs Next.js - The Smarter Alternative",
    descriptionAr: "لماذا Next.js بديل أفضل لـ Magento المعقد والمكلف",
    competitorSpeed: 5.0,
    nextjsSpeed: 0.8,
    competitorSEO: 70,
    nextjsSEO: 98,
    competitorSecurity: 70,
    nextjsSecurity: 99,
    competitorCost: 50000,
    nextjsCost: 6000,
    problems: [
      "معقد جداً ويحتاج خبراء",
      "تكلفة تطوير عالية جداً",
      "بطيء بدون تحسينات مكلفة",
      "استضافة خاصة مطلوبة",
      "صيانة مكلفة"
    ]
  },
  {
    slug: "opencart-vs-nextjs",
    competitor: "OpenCart",
    competitorAr: "أوبن كارت",
    titleAr: "أوبن كارت vs Next.js - الترقية المطلوبة",
    titleEn: "OpenCart vs Next.js - The Needed Upgrade",
    descriptionAr: "لماذا Next.js هو الترقية الطبيعية من OpenCart القديم",
    competitorSpeed: 3.5,
    nextjsSpeed: 0.8,
    competitorSEO: 55,
    nextjsSEO: 98,
    competitorSecurity: 55,
    nextjsSecurity: 99,
    competitorCost: 10000,
    nextjsCost: 6000,
    problems: [
      "تقنية قديمة",
      "SEO ضعيف",
      "ثغرات أمنية",
      "Extensions محدودة",
      "دعم مجتمعي ضعيف"
    ]
  },
  {
    slug: "prestashop-vs-nextjs",
    competitor: "PrestaShop",
    competitorAr: "بريستاشوب",
    titleAr: "بريستاشوب vs Next.js - المقارنة الكاملة",
    titleEn: "PrestaShop vs Next.js - Complete Comparison",
    descriptionAr: "مقارنة شاملة بين PrestaShop و Next.js للمتاجر الإلكترونية",
    competitorSpeed: 3.2,
    nextjsSpeed: 0.8,
    competitorSEO: 60,
    nextjsSEO: 98,
    competitorSecurity: 60,
    nextjsSecurity: 99,
    competitorCost: 12000,
    nextjsCost: 6000,
    problems: [
      "أداء متوسط",
      "Modules مدفوعة",
      "تحديثات تكسر الموقع",
      "دعم عربي ضعيف",
      "SEO يحتاج plugins"
    ]
  },
  {
    slug: "all-platforms",
    competitor: "All",
    competitorAr: "جميع المنصات",
    titleAr: "مقارنة شاملة لجميع منصات التجارة الإلكترونية",
    titleEn: "Complete Comparison of All Ecommerce Platforms",
    descriptionAr: "مقارنة WordPress, سلة, زد, Shopify, WooCommerce, Magento مع Next.js - أيهم أفضل؟",
    problems: []
  }
]

export const cities = [
  { slug: "riyadh", nameAr: "الرياض", nameEn: "Riyadh" },
  { slug: "jeddah", nameAr: "جدة", nameEn: "Jeddah" },
  { slug: "dammam", nameAr: "الدمام", nameEn: "Dammam" },
  { slug: "makkah", nameAr: "مكة المكرمة", nameEn: "Makkah" },
  { slug: "madinah", nameAr: "المدينة المنورة", nameEn: "Madinah" },
  { slug: "khobar", nameAr: "الخبر", nameEn: "Khobar" },
  { slug: "taif", nameAr: "الطائف", nameEn: "Taif" },
  { slug: "abha", nameAr: "أبها", nameEn: "Abha" },
  { slug: "tabuk", nameAr: "تبوك", nameEn: "Tabuk" },
  { slug: "buraidah", nameAr: "بريدة", nameEn: "Buraidah" },
  { slug: "khamis-mushait", nameAr: "خميس مشيط", nameEn: "Khamis Mushait" },
  { slug: "hail", nameAr: "حائل", nameEn: "Hail" },
  { slug: "najran", nameAr: "نجران", nameEn: "Najran" },
  { slug: "jubail", nameAr: "الجبيل", nameEn: "Jubail" },
  { slug: "yanbu", nameAr: "ينبع", nameEn: "Yanbu" },
  { slug: "dhahran", nameAr: "الظهران", nameEn: "Dhahran" },
  { slug: "qatif", nameAr: "القطيف", nameEn: "Qatif" },
  { slug: "hofuf", nameAr: "الهفوف", nameEn: "Hofuf" },
  { slug: "ras-tanura", nameAr: "رأس تنورة", nameEn: "Ras Tanura" },
  { slug: "sakaka", nameAr: "سكاكا", nameEn: "Sakaka" },
  { slug: "arar", nameAr: "عرعر", nameEn: "Arar" },
  { slug: "jizan", nameAr: "جيزان", nameEn: "Jizan" },
  { slug: "bisha", nameAr: "بيشة", nameEn: "Bisha" },
  { slug: "al-kharj", nameAr: "الخرج", nameEn: "Al-Kharj" },
  { slug: "unaizah", nameAr: "عنيزة", nameEn: "Unaizah" },
  { slug: "ar-rass", nameAr: "الرس", nameEn: "Ar-Rass" },
  { slug: "hafar-al-batin", nameAr: "حفر الباطن", nameEn: "Hafar Al-Batin" },
  { slug: "rabigh", nameAr: "رابغ", nameEn: "Rabigh" },
  { slug: "turayf", nameAr: "طريف", nameEn: "Turayf" },
  { slug: "al-qunfudhah", nameAr: "القنفذة", nameEn: "Al-Qunfudhah" },
  { slug: "al-majmah", nameAr: "المجمعة", nameEn: "Al-Majmah" },
  { slug: "al-aflaj", nameAr: "الأفلاج", nameEn: "Al-Aflaj" },
  { slug: "dawadmi", nameAr: "الدوادمي", nameEn: "Dawadmi" },
  { slug: "shaqra", nameAr: "شقراء", nameEn: "Shaqra" },
  { slug: "afif", nameAr: "عفيف", nameEn: "Afif" },
  { slug: "al-bahah", nameAr: "الباحة", nameEn: "Al-Bahah" },
  { slug: "al-lith", nameAr: "الليث", nameEn: "Al-Lith" },
  { slug: "al-wajh", nameAr: "الوجه", nameEn: "Al-Wajh" },
  { slug: "duba", nameAr: "ضبا", nameEn: "Duba" },
  { slug: "haql", nameAr: "حقل", nameEn: "Haql" },
  { slug: "umluj", nameAr: "أملج", nameEn: "Umluj" },
  { slug: "al-ula", nameAr: "العلا", nameEn: "Al-Ula" },
  { slug: "khaybar", nameAr: "خيبر", nameEn: "Khaybar" },
  { slug: "tayma", nameAr: "تيماء", nameEn: "Tayma" },
  { slug: "al-jawf", nameAr: "الجوف", nameEn: "Al-Jawf" },
  { slug: "zulfi", nameAr: "الزلفي", nameEn: "Zulfi" }
]

// Problems pages
export const ecommerceProblems = [
  { slug: "slow-wordpress-store", titleAr: "متجرك ووردبريس بطيء؟", descAr: "اكتشف لماذا متجرك بطيء وكيف تحله" },
  { slug: "salla-commission-fees", titleAr: "تعبت من عمولات سلة؟", descAr: "وفّر آلاف الريالات بالتخلص من عمولات سلة" },
  { slug: "zid-limitations", titleAr: "حدود زد تقيّدك؟", descAr: "احصل على حرية كاملة بدون قيود" },
  { slug: "woocommerce-security", titleAr: "مشاكل أمان ووكومرس؟", descAr: "حل نهائي لمشاكل أمان ووكومرس" },
  { slug: "slow-online-store", titleAr: "متجرك بطيء جداً؟", descAr: "سرّع متجرك 5X مع Next.js" },
  { slug: "google-ranking-problems", titleAr: "متجرك لا يظهر في جوجل؟", descAr: "حل SEO لمتجرك الإلكتروني" },
  { slug: "high-store-costs", titleAr: "تكاليف متجرك عالية؟", descAr: "وفّر 50% من تكاليف متجرك" },
  { slug: "poor-mobile-experience", titleAr: "تجربة موبايل سيئة؟", descAr: "متجر سريع على الموبايل" },
  { slug: "limited-customization", titleAr: "تخصيص محدود؟", descAr: "متجر مخصص 100% لعلامتك" },
  { slug: "no-seo-optimization", titleAr: "متجرك غير محسّن لـ SEO؟", descAr: "تحسين SEO شامل لمتجرك" },
  { slug: "platform-commissions", titleAr: "عمولات المنصة تأكل أرباحك؟", descAr: "متجر بدون أي عمولات" },
  { slug: "not-owning-your-store", titleAr: "لا تملك متجرك؟", descAr: "امتلك متجرك وكودك بالكامل" },
  { slug: "poor-customer-experience", titleAr: "تجربة عملاء سيئة؟", descAr: "تجربة عملاء ممتازة مع Next.js" },
  { slug: "cant-scale-store", titleAr: "متجرك لا يتحمل الضغط؟", descAr: "متجر يتحمل ملايين الزيارات" },
  { slug: "outdated-technology", titleAr: "تقنية متجرك قديمة؟", descAr: "ترقية لأحدث التقنيات" }
]
